Repository keesschollaart81/vscode-home-assistant, pull requests merged in 2020-09, with the labels that each got.

#609 Extract triggers from automation integration
  src/language-service/src/schemas/actions.ts
  src/language-service/src/schemas/integrations/automation.ts
  src/language-service/src/schemas/triggers.ts
Labels: chore

#610 Add support for shorthand template conditions
  src/language-service/src/schemas/conditions.ts
  src/language-service/src/schemas/types.ts
Labels: enhancement, yaml

#611 Add support for max_exceeded in automation and script run modes
  src/language-service/src/schemas/integrations/automation.ts
  src/language-service/src/schemas/integrations/script.ts
Labels: enhancement, yaml

#613 Add support for script and automation variables
  src/language-service/src/schemas/actions.ts
  src/language-service/src/schemas/integrations/automation.ts
  src/language-service/src/schemas/integrations/script.ts
Labels: enhancement, yaml

#614 Add the ability to reload bayesian integration
  package.json
  src/extension.ts
Labels: enhancement

#615 Add the ability to reload telegram integration
  package.json
  src/extension.ts
Labels: enhancement

#616 Add the ability to reload smtp integration
  package.json
  src/extension.ts
Labels: enhancement

#617 Add the ability to reload mqtt integration
  package.json
  src/extension.ts
Labels: enhancement

#618 Add the ability to reload rpi_gpio integration
  package.json
  src/extension.ts
Labels: enhancement

#619 Bump version to v1.9.0
  package-lock.json
  package.json
  src/language-service/package-lock.json
  src/language-service/package.json
Labels: chore

#633 Fix allow persons entities in zone conditions
  src/language-service/src/schemas/conditions.ts
Labels: bug, yaml

#668 Use common js version of HAWS
  package-lock.json
  package.json
  src/language-service/package.json
  src/language-service/src/home-assistant/haConnection.ts
  src/language-service/src/home-assistant/socket.ts
Labels: bug, dependencies

#669 Add media player device classes and update sensor classes
  src/language-service/src/schemas/types.ts
Labels: yaml

#670 Fix allow group integration without groups
  src/language-service/src/schemas/homeassistant.ts
Labels: bug, yaml

#658 Add property 'unique_id' to template sensor entry
  src/language-service/src/schemas/sensors.ts
Labels: yaml

#671 Fix missing name property for Media Control card
  src/language-service/src/schemas/ui-lovelace.ts
Labels: bug, yaml
