Repository keesschollaart81/vscode-home-assistant, pull requests merged in 2020-10, with the labels that each got.

#678 Accept secrets everywhere
  src/language-service/src/haLanguageService.ts
  src/language-service/src/schemas/core.ts
  src/language-service/src/schemas/integrations/hacs.ts
  src/language-service/src/schemas/integrations/http.ts
  src/language-service/src/schemas/integrations/panel_iframe.ts
  src/language-service/src/schemas/types.ts
Labels: enhancement, yaml

#683 Add confirmation property to actions schema
  src/language-service/src/schemas/ui-lovelace.ts
Labels: enhancement, yaml

#679 Add input_number schema
  src/language-service/src/schemas/homeassistant.ts
  src/language-service/src/schemas/integrations/index.d.ts
  src/language-service/src/schemas/integrations/input_number.ts
  src/language-service/src/schemas/mappings.json
Labels: enhancement, yaml

#680 Add counter schema
  src/language-service/src/schemas/homeassistant.ts
  src/language-service/src/schemas/integrations/counter.ts
  src/language-service/src/schemas/integrations/index.d.ts
Labels: enhancement, yaml

#681 Add special row button for entities schema
  src/language-service/src/schemas/ui-lovelace.ts
Labels: enhancement, yaml

#686 Allow any type in state trigger
  src/language-service/src/schemas/triggers.ts
Labels: yaml

#687 Added missing CastEntityConfig variables
  src/language-service/src/schemas/ui-lovelace.ts
Labels: yaml

#688 Add schema for template binary sensor
  src/language-service/src/schemas/homeassistant.ts
  src/language-service/src/schemas/integrations/binary_sensor.ts
  src/language-service/src/schemas/integrations/index.d.ts
  src/language-service/src/schemas/integrations/template.ts
  src/language-service/src/schemas/mappings.json
  src/language-service/src/schemas/platform.ts
Labels: enhancement, yaml

#692 Restructure and update sensor platform schema
  src/language-service/src/schemas/homeassistant.ts
  src/language-service/src/schemas/integrations/index.d.ts
  src/language-service/src/schemas/integrations/mqtt.ts
  src/language-service/src/schemas/integrations/sensor.ts
  src/language-service/src/schemas/integrations/template.ts
  src/language-service/src/schemas/mappings.json
  src/language-service/src/schemas/sensors.ts
Labels: chore, yaml

#693 Cleanup unused import from trigger schemas
  src/language-service/src/schemas/triggers.ts
Labels: chore

#695 Add schema for template cover
  src/language-service/src/schemas/homeassistant.ts
  src/language-service/src/schemas/integrations/cover.ts
  src/language-service/src/schemas/integrations/index.d.ts
  src/language-service/src/schemas/integrations/template.ts
  src/language-service/src/schemas/mappings.json
Labels: enhancement, yaml

#696 Add schema for template fan
  src/language-service/src/schemas/homeassistant.ts
  src/language-service/src/schemas/integrations/fan.ts
  src/language-service/src/schemas/integrations/index.d.ts
  src/language-service/src/schemas/integrations/template.ts
  src/language-service/src/schemas/mappings.json
Labels: enhancement, yaml

#697 Add schema for template light
  src/language-service/src/schemas/homeassistant.ts
  src/language-service/src/schemas/integrations/index.d.ts
  src/language-service/src/schemas/integrations/light.ts
  src/language-service/src/schemas/integrations/template.ts
  src/language-service/src/schemas/mappings.json
Labels: enhancement, yaml

#698 Add schema for template lock
  src/language-service/src/schemas/homeassistant.ts
  src/language-service/src/schemas/integrations/index.d.ts
  src/language-service/src/schemas/integrations/lock.ts
  src/language-service/src/schemas/integrations/template.ts
  src/language-service/src/schemas/mappings.json
Labels: enhancement, yaml

#699 Add schema for template switch
  src/language-service/src/schemas/homeassistant.ts
  src/language-service/src/schemas/integrations/index.d.ts
  src/language-service/src/schemas/integrations/switch.ts
  src/language-service/src/schemas/integrations/template.ts
  src/language-service/src/schemas/mappings.json
Labels: enhancement, yaml

#700 Add schema for template vacuum
  src/language-service/src/schemas/homeassistant.ts
  src/language-service/src/schemas/integrations/index.d.ts
  src/language-service/src/schemas/integrations/template.ts
  src/language-service/src/schemas/integrations/vacuum.ts
  src/language-service/src/schemas/mappings.json
Labels: enhancement, yaml

#682 Eslint path fix for windows
  package.json
  src/language-service/.eslintrc.js
  src/language-service/package.json
Labels: bug, hacktoberfest-accepted

#709 Fix typo in input_number mode property
  src/language-service/src/schemas/integrations/input_number.ts
Labels: bug, yaml

#710 Fix regular expression in known platforms
  src/language-service/src/schemas/integrations/alarm_control_panel.ts
  src/language-service/src/schemas/integrations/binary_sensor.ts
  src/language-service/src/schemas/integrations/cover.ts
  src/language-service/src/schemas/integrations/fan.ts
  src/language-service/src/schemas/integrations/light.ts
  src/language-service/src/schemas/integrations/lock.ts
  src/language-service/src/schemas/integrations/sensor.ts
  src/language-service/src/schemas/integrations/switch.ts
  src/language-service/src/schemas/integrations/vacuum.ts
Labels: bug, yaml

#712 Fix missing devices classes for the switch platform
  src/language-service/src/schemas/types.ts
Labels: bug, yaml

#713 Add full MQTT schema support
  src/language-service/src/schemas/homeassistant.ts
  src/language-service/src/schemas/integrations/alarm_control_panel.ts
  src/language-service/src/schemas/integrations/binary_sensor.ts
  src/language-service/src/schemas/integrations/camera.ts
  src/language-service/src/schemas/integrations/climate.ts
  src/language-service/src/schemas/integrations/cover.ts
  src/language-service/src/schemas/integrations/device_tracker.ts
  src/language-service/src/schemas/integrations/fan.ts
  src/language-service/src/schemas/integrations/index.d.ts
  src/language-service/src/schemas/integrations/light.ts
  src/language-service/src/schemas/integrations/lock.ts
  src/language-service/src/schemas/integrations/mqtt.ts
  src/language-service/src/schemas/integrations/mqtt_eventstream.ts
  src/language-service/src/schemas/integrations/mqtt_room.ts
  src/language-service/src/schemas/integrations/mqtt_statestream.ts
  src/language-service/src/schemas/integrations/sensor.ts
  src/language-service/src/schemas/integrations/vacuum.ts
  src/language-service/src/schemas/mappings.json
  src/language-service/src/schemas/types.ts
Labels: enhancement, yaml

#714 Add cloud schema support
  src/language-service/src/completionHelpers/entityIds.ts
  src/language-service/src/schemas/homeassistant.ts
  src/language-service/src/schemas/integrations/cloud.ts
  src/language-service/src/schemas/integrations/index.d.ts
Labels: enhancement, yaml

#717 Fix MQTT off_delay is optional
  src/language-service/src/schemas/integrations/mqtt.ts
Labels: bug, yaml

#723 Fix initial value type for input_number
  src/language-service/src/schemas/integrations/input_number.ts
Labels: bug, yaml

#730 Fix MQTT QOS and retain are optional
  src/language-service/src/schemas/integrations/mqtt.ts
Labels: bug, hacktoberfest-accepted, yaml

#739 Fix optional tilt_opened_value for MQTT cover
  src/language-service/src/schemas/integrations/mqtt.ts
Labels: bug, yaml
