Repository keesschollaart81/vscode-home-assistant, pull requests merged in 2020-07, with the labels that each got.

#391 Add release drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: chore

#392 Let Dependabot upgrade GitHub Actions
  .github/dependabot.yml
Labels: chore

#384 Fix mode typo in automation schema
  src/language-service/src/schemas/integrations/automation.ts
Labels: yaml

#383 Improve deprecation schema type
  src/language-service/src/schemas/types.ts
Labels: yaml

#382 Add schema for allowlist core config changes in HA 0.113.0
  src/language-service/src/schemas/core.ts
Labels: yaml

#409 Add Dependabot for the langhuage-service subpackage
  .github/dependabot.yml
Labels: chore

#408 Add attributes to secondary_info for Lovelace Entities Card
  src/language-service/src/schemas/ui-lovelace.ts
Labels: yaml

#397 Fix extension overwriting workspace files.associations
  src/extension.ts
Labels: bug

#334 Add trigger snippets
  src/snippets/homeassistant_automation.json
Labels: enhancement

#410 Fix automation & scene schema not parsed correctly with !include_dir_list
  src/language-service/src/schemas/integrations/automation.ts
  src/language-service/src/schemas/integrations/scene.ts
  src/language-service/src/schemas/mappings.json
Labels: yaml

#411 Fix API & service calls and template rendering
  package-lock.json
  package.json
  src/extension.ts
  src/language-service/package-lock.json
  src/language-service/package.json
  src/language-service/src/home-assistant/haConnection.ts
  src/server/server.ts
Labels: bug

#425 Cleanup useless template literal
  src/extension.ts
Labels: chore

#426 Add choose action schema
  src/language-service/src/schemas/actions.ts
Labels: yaml

#427 Fix device actions schema to allow for extra properties
  src/language-service/src/schemas/actions.ts
Labels: yaml

#428 Fix incorrect JSON schema type tag in property annotation
  src/language-service/src/schemas/types.ts
Labels: yaml

#429 Improve entity type validation
  src/language-service/src/schemas/actions.ts
  src/language-service/src/schemas/conditions.ts
  src/language-service/src/schemas/integrations/automation.ts
  src/language-service/src/schemas/integrations/group.ts
  src/language-service/src/schemas/types.ts
Labels: yaml

#430 Add max queue length property to automation
  src/language-service/src/schemas/integrations/automation.ts
Labels: yaml

#431 Bump Home Assistant JS WebSocket to 5.5.0
  package-lock.json
  package.json
  src/language-service/package-lock.json
  src/language-service/package.json
Labels: dependencies, javascript

#437 Fix using secrets with core elevation setting
  src/language-service/src/schemas/core.ts
Labels: yaml

#439 Bump version to v1.8.1
  package-lock.json
  package.json
  src/language-service/package-lock.json
  src/language-service/package.json
Labels: chore

#442 Fix number state condition strictness on entity_id
  src/language-service/src/schemas/conditions.ts
Labels: yaml

#444 Allow for person entities in zone trigger schema
  src/language-service/src/schemas/integrations/automation.ts
  src/language-service/src/schemas/types.ts
Labels: yaml

#445 Fix number state condition strictness on entity_id (#442)
  src/language-service/src/schemas/types.ts
Labels: yaml
