Repository keesschollaart81/vscode-home-assistant, pull requests merged in 2020-11, with the labels that each got.

#792 Downgrade json languageservice to 3.9.1
  package-lock.json
  package.json
  src/language-service/package-lock.json
  src/language-service/package.json
Labels: dependencies

#793 Exclude dependency upgrades from generated release notes
  .github/release-drafter.yml
Labels: chore

#794 Fix MQTT device tracker devices list
  src/language-service/src/schemas/integrations/mqtt.ts
Labels: bug, yaml

#808 Fix temp_step property in MQTT Climate
  src/language-service/src/schemas/integrations/mqtt.ts
Labels: bug, yaml

#813 Add support for media_dirs core configuration
  src/language-service/src/schemas/core.ts
Labels: yaml

#821 Add placeholder tag support
  src/language-service/src/haConfig/haYamlFile.ts
  src/language-service/src/haLanguageService.ts
Labels: enhancement, yaml

#816 Fixes bug where "Go to definition" was broken when paths were wrapped in quotes
  src/language-service/src/definition/includes.ts
Labels: bug

#747 Add Tag trigger
  src/language-service/src/schemas/triggers.ts
Labels: enhancement, yaml

#835 Add Lovelace integration schema
  src/language-service/src/schemas/homeassistant.ts
  src/language-service/src/schemas/integrations/index.d.ts
  src/language-service/src/schemas/integrations/lovelace.ts
Labels: enhancement, yaml

#842 Add full Lovelace schema support
  src/language-service/src/completionHelpers/entityIds.ts
  src/language-service/src/schemas/lovelace/actions.ts
  src/language-service/src/schemas/lovelace/cards/alarm_panel.ts
  src/language-service/src/schemas/lovelace/cards/button.ts
  src/language-service/src/schemas/lovelace/cards/calendar.ts
  src/language-service/src/schemas/lovelace/cards/conditional.ts
  src/language-service/src/schemas/lovelace/cards/custom.ts
  src/language-service/src/schemas/lovelace/cards/entities.ts
  src/language-service/src/schemas/lovelace/cards/entity.ts
  src/language-service/src/schemas/lovelace/cards/entity_button.ts
  src/language-service/src/schemas/lovelace/cards/entity_filter.ts
  src/language-service/src/schemas/lovelace/cards/gauge.ts
  src/language-service/src/schemas/lovelace/cards/glance.ts
  src/language-service/src/schemas/lovelace/cards/grid.ts
  src/language-service/src/schemas/lovelace/cards/history_graph.ts
  src/language-service/src/schemas/lovelace/cards/horizontal_stack.ts
  src/language-service/src/schemas/lovelace/cards/humidifier.ts
  src/language-service/src/schemas/lovelace/cards/iframe.ts
  src/language-service/src/schemas/lovelace/cards/index.d.ts
  src/language-service/src/schemas/lovelace/cards/light.ts
  src/language-service/src/schemas/lovelace/cards/logbook.ts
  src/language-service/src/schemas/lovelace/cards/map.ts
  src/language-service/src/schemas/lovelace/cards/markdown.ts
  src/language-service/src/schemas/lovelace/cards/media_control.ts
  src/language-service/src/schemas/lovelace/cards/picture.ts
  src/language-service/src/schemas/lovelace/cards/picture_elements.ts
  src/language-service/src/schemas/lovelace/cards/picture_entity.ts
  src/language-service/src/schemas/lovelace/cards/picture_glance.ts
  src/language-service/src/schemas/lovelace/cards/plant_status.ts
  src/language-service/src/schemas/lovelace/cards/sensor.ts
  src/language-service/src/schemas/lovelace/cards/shopping_list.ts
  src/language-service/src/schemas/lovelace/cards/thermostat.ts
  src/language-service/src/schemas/lovelace/cards/vertical_stack.ts
  src/language-service/src/schemas/lovelace/cards/weather_forecast.ts
  src/language-service/src/schemas/lovelace/dashboard.ts
  src/language-service/src/schemas/lovelace/elements.ts
  src/language-service/src/schemas/lovelace/headers_footers.ts
  src/language-service/src/schemas/lovelace/rows.ts
  src/language-service/src/schemas/lovelace/types.ts
  src/language-service/src/schemas/lovelace/view.ts
  src/language-service/src/schemas/mappings.json
  src/language-service/src/schemas/types.ts
  src/language-service/src/schemas/ui-lovelace.ts
Labels: bug, enhancement, yaml
