Repository keesschollaart81/vscode-home-assistant, pull requests merged in 2020-08, with the labels that each got.

#453 Add snippets and remove snippets leading spaces
  src/snippets/homeassistant_automation.json
Labels: bug, enhancement

#485 Minor typo/formatting fixes
  .github/ISSUE_TEMPLATE/1. yaml-error-or-warning.md
  README.md
  src/language-service/src/haLanguageService.ts
  src/language-service/src/schemas/generateSchemas.ts
Labels: bug, documentation

#554 Add support for attributes in (numeric) state conditions
  src/language-service/src/schemas/conditions.ts
Labels: yaml

#553 Add support for attributes in state/numeric state trigger
  src/language-service/src/schemas/integrations/automation.ts
Labels: yaml

#552 Add support for multiple times and input_datetime entities in time triggers
  src/language-service/src/schemas/integrations/automation.ts
  src/language-service/src/schemas/types.ts
Labels: yaml

#555 Data template changes in service calls
  src/language-service/src/schemas/actions.ts
  src/language-service/src/schemas/types.ts
  src/snippets/homeassistant_automation.json
Labels: yaml

#551 Add the ability to reload HomeKit
  package.json
  src/extension.ts
Labels: enhancement

#556 Fix number state trigger strictness on entity_id
  src/language-service/src/schemas/integrations/automation.ts
Labels: bug, yaml

#557 Fix Core packages root schema
  src/language-service/src/schemas/core.ts
Labels: bug, yaml

#558 Add the ability to reload filesize integration
  package.json
  src/extension.ts
Labels: enhancement

#559 Add support for wait for trigger action
  src/language-service/src/schemas/actions.ts
  src/language-service/src/schemas/integrations/automation.ts
Labels: enhancement, yaml

#560 Add support for reloading min_max
  package.json
  src/extension.ts
Labels: enhancement

#561 Remove occurrences of Hass.io
  package.json
Labels: chore

#562 Add the ability to reload generic_thermostat integration
  package.json
  src/extension.ts
Labels: enhancement

#563 Add the ability to reload generic camera integration
  package.json
  src/extension.ts
Labels: enhancement

#564 Add the ability to reload ping integration
  package.json
  src/extension.ts
Labels: enhancement

#565 Add the ability to reload trend integration
  package.json
  src/extension.ts
Labels: enhancement

#566 Add the ability to reload history_stats integration
  package.json
  src/extension.ts
Labels: enhancement

#567 Add the ability to reload universal media player
  package.json
  src/extension.ts
Labels: enhancement

#568 Add the ability to reload statistics integration
  package.json
  src/extension.ts
Labels: enhancement

#569 Add the ability to reload filter integration
  package.json
  src/extension.ts
Labels: enhancement

#570 Add support for reloading REST integration
  package.json
  src/extension.ts
Labels: enhancement

#571 Add missing Lovelace attribute property to Entity card
  src/language-service/src/schemas/ui-lovelace.ts
Labels: yaml

#572 Add support for reloading command_line integration
  package.json
  src/extension.ts
Labels: enhancement

#573 Add support for Lovelace URL action
  src/language-service/src/schemas/ui-lovelace.ts
Labels: yaml

#574 Fix option state-filter in Lovelace picture elements card
  src/language-service/src/schemas/ui-lovelace.ts
Labels: bug, yaml
