Repository keesschollaart81/vscode-home-assistant, pull requests merged in 2021-05, with the labels that each got.

#1193 Add auto-completion for light and lights
  src/language-service/src/completionHelpers/entityIds.ts
Labels: enhancement

#1217 Fix shorthand scene state notation
  src/language-service/src/schemas/integrations/core/scene.ts
Labels: bug

#1218 Add support for script Blueprints
  src/language-service/src/haConfig/haConfig.ts
  src/language-service/src/schemas/integrations/core/blueprint.ts
  src/language-service/src/schemas/integrations/core/script.ts
  src/language-service/src/schemas/mappings.json
  src/language-service/src/schemas/schemaService.ts
Labels: enhancement, yaml

#1219 Fix script via include_dir_named
  src/language-service/src/schemas/integrations/core/script.ts
  src/language-service/src/schemas/mappings.json
Labels: bug

#1220 Add MQTT Number platform support
  src/language-service/src/schemas/configuration.ts
  src/language-service/src/schemas/integrations/core/index.d.ts
  src/language-service/src/schemas/integrations/core/mqtt.ts
  src/language-service/src/schemas/integrations/core/number.ts
  src/language-service/src/schemas/mappings.json
Labels: enhancement

#1221 Add support for MQTT availability mode
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: enhancement

#1231 Add min/max/step to MQTT number
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: enhancement

#1232 Add MQTT fan feat for resetting current speed percentage or preset_mode
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: enhancement

#1233 Add KNX support
  src/language-service/src/schemas/configuration.ts
  src/language-service/src/schemas/integrations/core/index.d.ts
  src/language-service/src/schemas/integrations/core/knx.ts
  src/language-service/src/schemas/types.ts
Labels: enhancement

#1251 Add support for effects, transition/brightness parameters to template light, min_mireds and max_mireds templates
  src/language-service/src/schemas/integrations/core/template.ts
Labels: enhancement

#1252 Add MQTT sensor state_class
  src/language-service/src/schemas/integrations/core/template.ts
  src/language-service/src/schemas/types.ts
Labels: enhancement

#1258 Fix incorrect deprecated value_template in MQTT cover
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: bug
