Repository keesschollaart81/vscode-home-assistant, pull requests merged in 2021-01, with the labels that each got.

#935 GitHub Actions: Node 14 + make them pretty
  .github/workflows/github-actions-language-service.yml
  .github/workflows/github-actions-vscode-extension.yml
Labels: chore, dependencies

#953 Add the ability to reload template sensors
  package.json
  src/extension.ts
Labels: enhancement

#954 Improve auto indent on pasting YAML
  package.json
Labels: bug
