Repository keesschollaart81/vscode-home-assistant, pull requests merged in 2021-07, with the labels that each got.

#1387 Add support for trace settings in scripts and automations
  src/language-service/src/schemas/integrations/core/automation.ts
  src/language-service/src/schemas/integrations/core/script.ts
Labels: enhancement

#1394 Fix missing unique_id in Weather template
  src/language-service/src/schemas/integrations/core/template.ts
Labels: bug

#1388 Add onLanguage activation event
  package.json
Labels: enhancement

#1395 Ignore hidden files and folders
  src/server/fileAccessor.ts
Labels: bug

#1396 Add support for trigger_variables in automations
  src/language-service/src/schemas/integrations/core/automation.ts
Labels: enhancement

#1421 Add unique_id support to light groups
  src/language-service/src/schemas/integrations/core/group.ts
Labels: enhancement

#1442 KNX hs-color
  src/language-service/src/schemas/integrations/core/knx.ts
Labels: enhancement

#1460 Bump nvmrc
  .nvmrc
Labels: dependencies

#1461 Add support for currency in core configuration
  src/language-service/src/schemas/integrations/core/homeassistant.ts
  src/language-service/src/schemas/types.ts
Labels: enhancement
