Repository keesschollaart81/vscode-home-assistant, pull requests merged in 2021-03, with the labels that each got.

#1031 Target now supports templates
  src/language-service/src/schemas/integrations/actions.ts
Labels: yaml

#1032 Aliases are now supported in all actions and conditions
  src/language-service/src/schemas/integrations/actions.ts
  src/language-service/src/schemas/integrations/conditions.ts
Labels: yaml

#1034 Support value_template in MQTT trigger
  src/language-service/src/schemas/integrations/triggers.ts
Labels: yaml

#1033 Collection of tweak to snippets
  src/snippets/homeassistant_automation.json
  src/snippets/homeassistant_sensor.json
Labels: yaml

#1035 Add support for weather templates
  src/language-service/src/schemas/configuration.ts
  src/language-service/src/schemas/integrations/core/index.d.ts
  src/language-service/src/schemas/integrations/core/template.ts
  src/language-service/src/schemas/integrations/core/weather.ts
  src/language-service/src/schemas/mappings.json
Labels: enhancement

#1036 Remove unused vscode-test
  package-lock.json
  package.json
Labels: chore

#1068 Fixes 'square' parameter for the Grid card to be a boolean
  src/language-service/src/schemas/lovelace/cards/grid.ts
Labels: bug, yaml

#1069 Explicitly build a full schema in CI
  .github/workflows/github-actions-language-service.yml
  .github/workflows/github-actions-vscode-extension.yml
Labels: chore

#1074 Make severity optional in gauge card for Lovelace schema
  src/language-service/src/schemas/lovelace/cards/gauge.ts
Labels: bug, yaml

#1085 Added state_stopped attribute to a MQTT Cover
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: yaml

#1086 Update MQTT Cover schema to match Home Assistant 2021.3.0
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: yaml

#1075 Update template.ts to include 2013.3 fan change
  src/language-service/src/schemas/integrations/core/template.ts
Labels: yaml

#1092 Integrations in selectors are domains too
  src/language-service/src/schemas/integrations/selectors.ts
Labels: yaml

#1093 Add auto-completion support for Domains
  src/language-service/src/completionHelpers/domains.ts
  src/language-service/src/haLanguageService.ts
  src/language-service/src/home-assistant/haConnection.ts
Labels: enhancement

#1094 Simplify automation Blueprint schema
  src/language-service/src/schemas/integrations/core/automation.ts
  src/language-service/src/schemas/integrations/core/blueprint.ts
  src/language-service/src/schemas/mappings.json
Labels: yaml

#1096 Ignore !input and !include errors across the board
  src/language-service/src/haLanguageService.ts
Labels: enhancement

#1097 Blueprint input default can be any type
  src/language-service/src/schemas/integrations/core/blueprint.ts
Labels: yaml

#1100 Allow use boolean as state in state conditon
  src/language-service/src/schemas/types.ts
Labels: yaml

#1119 Add Spotify integration support
  src/language-service/src/schemas/configuration.ts
  src/language-service/src/schemas/integrations/core/index.d.ts
  src/language-service/src/schemas/integrations/core/spotify.ts
Labels: yaml

#1120 Add updater integration support
  src/language-service/src/schemas/configuration.ts
  src/language-service/src/schemas/integrations/core/index.d.ts
  src/language-service/src/schemas/integrations/core/updater.ts
Labels: yaml

#1121 Add icon support to MQTT platforms
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: yaml

#1122 Add template support for remaining attributes of weather template
  src/language-service/src/schemas/integrations/core/template.ts
Labels: yaml

#1124 Service target can be a template by itself
  src/language-service/src/schemas/integrations/actions.ts
Labels: yaml

#1123 Add UI selectors to scripts
  src/language-service/src/schemas/integrations/core/script.ts
Labels: yaml
