Repository keesschollaart81/vscode-home-assistant, pull requests merged in 2022-03, with the labels that each got.

#1983 :arrow_down: vscode-json-languageservice to 3.9.1
  package-lock.json
  package.json
  src/language-service/package-lock.json
  src/language-service/package.json
Labels: dependencies

#1986 Add support for trigger variables
  src/language-service/src/schemas/integrations/triggers.ts
Labels: enhancement

#1985 :ambulance: Fix schema collisions between platforms and template
  src/language-service/src/schemas/integrations/core/template.ts
  src/language-service/src/schemas/mappings.json
Labels: bug

#1908 Add support for binary sensor tod
  src/language-service/src/schemas/integrations/core/binary_sensor.ts
  src/language-service/src/schemas/integrations/core/tod.ts
Labels: enhancement

#1987 Add support for shorthand conditions
  src/language-service/src/schemas/integrations/conditions.ts
  src/language-service/src/schemas/integrations/core/automation.ts
Labels: enhancement

#1988 :ambulance: Fix typo in stat_type
  src/language-service/src/schemas/integrations/conditions.ts
  src/language-service/src/schemas/integrations/core/automation.ts
  src/language-service/src/schemas/lovelace/cards/statistics_graph.ts
Labels: bug

#2005 Fix input_text initial type
  src/language-service/src/schemas/integrations/core/input_text.ts
Labels: bug
