Repository keesschollaart81/vscode-home-assistant, pull requests merged in 2022-05, with the labels that each got.

#2097 Update nodejs to 16
  .github/workflows/github-actions-language-service.yml
  .github/workflows/github-actions-vscode-extension.yml
  .nvmrc
Labels: dependencies

#2101 Update home-assistant-js-websocket to 7.0.5
  package-lock.json
  package.json
  src/language-service/package-lock.json
  src/language-service/package.json
Labels: bug

#2104 Fix empty objects for selector configuration
  src/language-service/src/schemas/integrations/selectors.ts
Labels: bug

#2111 Render templates in strict mode
  src/server/server.ts
Labels: bug

#2118 Add KNX Cover `invert_updown` option
  src/language-service/src/schemas/integrations/core/knx.ts
Labels: enhancement

#2132 Handle frontend metadata correctly in service calls
  src/language-service/src/schemas/integrations/actions.ts
Labels: enhancement
