Repository keesschollaart81/vscode-home-assistant, pull requests merged in 2022-09, with the labels that each got.

#2277 Add alias for triggers
  src/language-service/src/schemas/integrations/triggers.ts
Labels: enhancement

#2169 Add command template option to climate mqtt integration
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: enhancement

#2205 Add units to weather template integration
  src/language-service/src/schemas/integrations/core/template.ts
  src/language-service/src/schemas/types.ts
Labels: enhancement

#2279 Remove deprecated platform configuration for MQTT
  src/language-service/src/schemas/integrations/core/alarm_control_panel.ts
  src/language-service/src/schemas/integrations/core/binary_sensor.ts
  src/language-service/src/schemas/integrations/core/camera.ts
  src/language-service/src/schemas/integrations/core/climate.ts
  src/language-service/src/schemas/integrations/core/cover.ts
  src/language-service/src/schemas/integrations/core/device_tracker.ts
  src/language-service/src/schemas/integrations/core/fan.ts
  src/language-service/src/schemas/integrations/core/light.ts
  src/language-service/src/schemas/integrations/core/lock.ts
  src/language-service/src/schemas/integrations/core/mqtt.ts
  src/language-service/src/schemas/integrations/core/number.ts
  src/language-service/src/schemas/integrations/core/select.ts
  src/language-service/src/schemas/integrations/core/sensor.ts
  src/language-service/src/schemas/integrations/core/vacuum.ts
Labels: yaml

#2280 Clean up YAML configuration for Uptime
  src/language-service/src/schemas/configuration.ts
  src/language-service/src/schemas/integrations/core/index.d.ts
  src/language-service/src/schemas/integrations/core/updater.ts
Labels: yaml

#2281 Clean up YAML schema deprecations
  src/language-service/src/schemas/integrations/conditions.ts
  src/language-service/src/schemas/integrations/core/automation.ts
  src/language-service/src/schemas/integrations/core/homeassistant.ts
  src/language-service/src/schemas/integrations/core/knx.ts
  src/language-service/src/schemas/integrations/core/mqtt.ts
  src/language-service/src/schemas/integrations/core/template.ts
  src/language-service/src/schemas/lovelace/dashboard.ts
  src/language-service/src/schemas/lovelace/view.ts
Labels: yaml

#2282 Fix MQTT button marked as invalid
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: bug

#2283 Fix for_each repeat action validation
  src/language-service/src/schemas/integrations/actions.ts
Labels: bug
