Repository keesschollaart81/vscode-home-assistant, pull requests merged in 2022-01, with the labels that each got.

#1815 Update HACS token schema
  README.md
  src/language-service/src/schemas/integrations/custom/hacs.ts
Labels: bug

#1829 Add support for input button
  src/language-service/src/schemas/configuration.ts
  src/language-service/src/schemas/integrations/core/index.d.ts
  src/language-service/src/schemas/integrations/core/input_button.ts
  src/language-service/src/schemas/mappings.json
Labels: enhancement

#1830 Fix buttons entity row
  src/language-service/src/schemas/lovelace/rows.ts
Labels: bug

#1831 Add file inclusion support for input_*
  src/language-service/src/schemas/integrations/core/input_boolean.ts
  src/language-service/src/schemas/integrations/core/input_button.ts
  src/language-service/src/schemas/integrations/core/input_number.ts
  src/language-service/src/schemas/mappings.json
Labels: enhancement

#1832 Add state_color to Entity card
  src/language-service/src/schemas/lovelace/cards/entity.ts
Labels: enhancement

#1833 Add support for the Area card
  src/language-service/src/schemas/lovelace/cards/area.ts
  src/language-service/src/schemas/lovelace/cards/index.d.ts
  src/language-service/src/schemas/lovelace/types.ts
Labels: enhancement

#1834 Add support for binary sensor groups
  src/language-service/src/schemas/integrations/core/binary_sensor.ts
  src/language-service/src/schemas/integrations/core/group.ts
Labels: enhancement

#1835 Add support for input datetime
  src/language-service/src/schemas/configuration.ts
  src/language-service/src/schemas/integrations/core/index.d.ts
  src/language-service/src/schemas/integrations/core/input_datetime.ts
  src/language-service/src/schemas/mappings.json
Labels: enhancement

#1836 Add support for input select
  src/language-service/src/schemas/configuration.ts
  src/language-service/src/schemas/integrations/core/index.d.ts
  src/language-service/src/schemas/integrations/core/input_select.ts
  src/language-service/src/schemas/mappings.json
Labels: enhancement

#1837 Add support for input text
  src/language-service/src/schemas/configuration.ts
  src/language-service/src/schemas/integrations/core/index.d.ts
  src/language-service/src/schemas/integrations/core/input_select.ts
  src/language-service/src/schemas/integrations/core/input_text.ts
  src/language-service/src/schemas/mappings.json
Labels: enhancement

#1845 Add Jinja2 inside yaml files support #78
  package.json
  syntaxes/external/YAML.tmLanguage
  syntaxes/external/jinja.tmLanguage.json
  syntaxes/home-assistant/generated/jinja-braces-block.tmLanguage
  syntaxes/home-assistant/generated/jinja-braces.tmLanguage
  syntaxes/home-assistant/generated/jinja-conditionals.tmLanguage
  syntaxes/home-assistant/generated/jinja-double-quote-escape.tmLanguage
  syntaxes/home-assistant/generated/jinja-extras.tmLanguage
  syntaxes/home-assistant/generated/jinja-keywords.tmLanguage
  syntaxes/home-assistant/generated/jinja-single-quote-escape.tmLanguage
  syntaxes/jinja-language-configuration.json
  syntaxes/yaml-language-configuration.json
  yaml-language/yaml.tmLanguage.json
Labels: enhancement

#1854 Change Jinja keywords regex layout to make it sortable/maintainable
  syntaxes/home-assistant/jinja-keywords.tmLanguage
Labels: enhancement

#1855 Add period option for statistics graph
  src/language-service/src/schemas/lovelace/cards/statistics_graph.ts
Labels: enhancement

#1857 Cleanup Hue integration YAML syntax
  src/language-service/src/schemas/configuration.ts
  src/language-service/src/schemas/integrations/core/hue.ts
  src/language-service/src/schemas/integrations/core/index.d.ts
Labels: chore

#1858 Fix MQTT fan requires deprecated option
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: bug

#1856 Add built-in Jinja2 keywords
  syntaxes/home-assistant/jinja-keywords.tmLanguage
Labels: enhancement

#1859 Add support for modern template entities syntax
  src/language-service/src/schemas/configuration.ts
  src/language-service/src/schemas/integrations/core/index.d.ts
  src/language-service/src/schemas/integrations/core/template.ts
  src/language-service/src/schemas/mappings.json
Labels: enhancement

#1861 Add new device_classes to (binary) sensors
  src/language-service/src/schemas/types.ts
Labels: enhancement

#1885 Added count filter
  syntaxes/home-assistant/jinja-keywords.tmLanguage
Labels: bug
