Repository keesschollaart81/vscode-home-assistant, pull requests merged in 2022-04, with the labels that each got.

#2016 Add KNX sensor type `latin_1`
  src/language-service/src/schemas/integrations/core/knx.ts
Labels: enhancement

#2013 Add "running" to DeviceClassesBinarySensor
  src/language-service/src/schemas/types.ts
Labels: enhancement

#2031 Add support for the Template selector
  src/language-service/src/schemas/integrations/selectors.ts
Labels: enhancement

#2032 Add support for the foreach repeat action
  src/language-service/src/schemas/integrations/actions.ts
Labels: enhancement

#2033 Add support for not_from and not_to in state trigger
  src/language-service/src/schemas/integrations/triggers.ts
Labels: enhancement

#2035 Add support for shorthand logic conditions
  src/language-service/src/schemas/integrations/conditions.ts
Labels: enhancement

#2036 Add support for the if-then action
  src/language-service/src/schemas/integrations/actions.ts
Labels: enhancement

#2038 Add support for match any in a state condition
  src/language-service/src/schemas/integrations/conditions.ts
Labels: enhancement

#2037 Add support for the parallel action
  src/language-service/src/schemas/integrations/actions.ts
Labels: enhancement

#2040 Update home-assistant-js-websocket to 7.0.3
  package-lock.json
  package.json
  src/language-service/package-lock.json
  src/language-service/package.json
Labels: dependencies

#2039 Add support for enabling/disabling action/conditions/triggers
  src/language-service/src/schemas/integrations/actions.ts
  src/language-service/src/schemas/integrations/conditions.ts
  src/language-service/src/schemas/integrations/triggers.ts
Labels: enhancement

#2041 Add MQTT availability_template support
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: enhancement

#2042 Set HA version on WebSocket
  src/language-service/src/home-assistant/socket.ts
Labels: bug

#2055 Add duration sensor device class
  src/language-service/src/schemas/types.ts
Labels: enhancement

#2046 Add KNX notify `type` option
  src/language-service/src/schemas/integrations/core/knx.ts
Labels: enhancement
