Repository keesschollaart81/vscode-home-assistant, pull requests merged in 2023-01, with the labels that each got.

#2452 Add support for Intent Scripts
  src/language-service/src/schemas/configuration.ts
  src/language-service/src/schemas/integrations/core/index.d.ts
  src/language-service/src/schemas/integrations/core/intent_script.ts
Labels: enhancement

#2453 Clean up bunch of linters
  .eslintrc.js
  package-lock.json
  package.json
Labels: dependencies

#2454 Clean up bunch of linters from language service
  src/language-service/package-lock.json
  src/language-service/package.json
Labels: dependencies

#2455 More cleanup of linters, use eslint recommended
  .eslintrc.js
  package-lock.json
  package.json
  src/language-service/.eslintrc.js
  src/language-service/package-lock.json
  src/language-service/package.json
  src/language-service/src/haConfig/haYamlFile.ts
  src/language-service/src/home-assistant/socket.ts
  src/language-service/src/schemas/configuration.ts
  src/language-service/src/schemas/generateSchemas.ts
  src/language-service/src/schemas/lovelace/types.ts
  src/server/server.ts
Labels: dependencies

#2457 Add input_button to input reload domains
  src/extension.ts
Labels: enhancement

#2456 Add conversation config
  src/language-service/src/schemas/configuration.ts
  src/language-service/src/schemas/integrations/core/conversation.ts
  src/language-service/src/schemas/integrations/core/index.d.ts
Labels: enhancement

#2458 Add support for reloading conversation intents
  package.json
  src/extension.ts
Labels: enhancement

#2439 Add unique_id to schema for mqtt_room sensor platform
  src/language-service/src/schemas/integrations/core/mqtt_room.ts
Labels: enhancement

#2432 fix mqtt schema [device]/identifiers] unknown
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: bug
