Repository keesschollaart81/vscode-home-assistant, pull requests merged in 2024-09, with the labels that each got.

#3139 Remove unneeded debug log
  src/language-service/src/haConfig/haYamlFile.ts
Labels: chore

#3140 Don't resolve symlinks when assigning schemas
  src/language-service/src/schemas/schemaService.ts
Labels: bug

#3142 Add license, upgrade to Node 18, fix publish
  .github/workflows/github-actions-vscode-extension.yml
  .nvmrc
  LICENSE.md
  README.md
Labels: bug

#3137 Fix schema generation issue and support `action` key
  src/language-service/src/schemas/integrations/actions.ts
  src/language-service/src/schemas/integrations/core/camera.ts
  src/language-service/src/schemas/integrations/core/climate.ts
  src/language-service/src/schemas/integrations/core/cover.ts
  src/language-service/src/schemas/integrations/core/fan.ts
  src/language-service/src/schemas/integrations/core/http.ts
  src/language-service/src/schemas/integrations/core/light.ts
  src/language-service/src/schemas/integrations/core/lock.ts
  src/language-service/src/schemas/integrations/core/update.ts
  src/language-service/src/schemas/integrations/core/vacuum.ts
  src/language-service/src/schemas/integrations/core/weather.ts
  src/language-service/src/schemas/types.ts
Labels: bug

#3135 Accept bare number as configuration for sync_state
  src/language-service/src/schemas/integrations/core/knx.ts
Labels: enhancement

#3132 Fix calendar initial_view: "list" > "listWeek"
  src/language-service/src/schemas/lovelace/cards/calendar.ts
Labels: bug

#3121 Add `floor_id` to service actions
  src/language-service/src/schemas/integrations/actions.ts
  src/language-service/src/schemas/types.ts
Labels: yaml

#3066 Introduce new entityIds keyword alias "group_members"
  src/language-service/src/completionHelpers/entityIds.ts
Labels: enhancement

#3148 Add support for targeting labels
  src/language-service/src/schemas/integrations/actions.ts
  src/language-service/src/schemas/types.ts
Labels: yaml

#3149 Add support for plural automation keys
  src/language-service/src/schemas/integrations/core/automation.ts
Labels: yaml

#3152 Fix Plural automation schema
  src/language-service/src/schemas/integrations/core/automation.ts
Labels: bug

#3155 Update forecast template fields
  src/language-service/src/schemas/integrations/core/template.ts
Labels: yaml

#3156 Add value_template to number.mqtt
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: yaml

#3179 Extend YAML properties of weather template
  src/language-service/src/schemas/integrations/core/template.ts
Labels: yaml

#3180 Add sequence action support
  src/language-service/src/schemas/integrations/actions.ts
Labels: yaml

#3181 Add support for multiple text fields in text selector
  src/language-service/src/schemas/integrations/selectors.ts
Labels: yaml
