Repository keesschollaart81/vscode-home-assistant, pull requests merged in 2024-10, with the labels that each got.

#3192 Fix blueprint input, as it is optional
  src/language-service/src/schemas/integrations/core/automation.ts
  src/language-service/src/schemas/integrations/core/script.ts
Labels: bug

#3197 Add legacy syntax errors for old style automation YAML
  src/language-service/src/schemas/integrations/actions.ts
  src/language-service/src/schemas/integrations/selectors.ts
  src/language-service/src/schemas/integrations/triggers.ts
  src/language-service/src/schemas/types.ts
Labels: yaml

#3198 Add area_id auto-completion
  src/language-service/src/completionHelpers/areas.ts
  src/language-service/src/haLanguageService.ts
  src/language-service/src/home-assistant/haConnection.ts
Labels: enhancement

#3202 add missing use_x_frame_options to http
  src/language-service/src/schemas/integrations/core/http.ts
Labels: yaml

#3204 Add support for blueprint collapsable sections
  src/language-service/src/schemas/integrations/core/blueprint.ts
Labels: yaml

#3205 Clean up removed MQTT YAML configuration
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: yaml

#3206 Add support for the assist pipeline selector
  src/language-service/src/schemas/integrations/selectors.ts
Labels: yaml

#3207 Add support for the backup location selector
  src/language-service/src/schemas/integrations/selectors.ts
Labels: yaml

#3208 Add support for the constant selector
  src/language-service/src/schemas/integrations/selectors.ts
Labels: yaml

#3209 Add support for the conversation agent selector
  src/language-service/src/schemas/integrations/selectors.ts
Labels: yaml

#3210 Add support for the country selector
  src/language-service/src/schemas/integrations/selectors.ts
Labels: yaml

#3212 Add support for the floor selector
  src/language-service/src/schemas/integrations/selectors.ts
Labels: yaml

#3211 Add enable_milisecond suppor to duration selector
  src/language-service/src/schemas/integrations/selectors.ts
Labels: yaml

#3213 Add support for the label selector
  src/language-service/src/schemas/integrations/selectors.ts
Labels: yaml

#3214 Add support for the language selector
  src/language-service/src/schemas/integrations/selectors.ts
Labels: yaml

#3215 Add support for the QR Code selector
  src/language-service/src/schemas/integrations/selectors.ts
Labels: yaml

#3216 Add support for the trigger selector
  src/language-service/src/schemas/integrations/selectors.ts
Labels: yaml

#3217 Fix MQTT schema for list type based configuration
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: bug

#3223 Add modern syntax for tap_action in Dashboards
  src/language-service/src/schemas/lovelace/actions.ts
Labels: yaml

#3224 Extend MQTT device information properties
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: yaml

#3234 Fix persistent notification trigger schema
  src/language-service/src/schemas/integrations/triggers.ts
Labels: yaml
