Repository keesschollaart81/vscode-home-assistant, pull requests merged in 2025-07, with the labels that each got.

#3664 Update template.ts by switch
  src/language-service/src/schemas/integrations/core/template.ts
Labels: yaml

#3693 Skip commented out YAML lines for existence checks
  src/language-service/src/haLanguageService.ts
  src/test/suite/area-validation-mock.test.ts
  src/test/suite/device-validation-mock.test.ts
  src/test/suite/entity-validation.test.ts
  src/test/suite/floor-validation-mock.test.ts
  src/test/suite/label-validation-mock.test.ts
  src/test/suite/secrets-validation-mock.test.ts
  src/test/suite/service-validation-mock.test.ts
Labels: enhancement

#3695 Fixes action does not exists outside of action context
  src/language-service/src/haLanguageService.ts
  src/test/suite/automation-trigger-issue-3623.test.ts
  src/test/suite/service-validation-mock.test.ts
Labels: bug

#3696 Auto-render templates on hovering over them
  package.json
  src/language-service/src/configuration.ts
  src/language-service/src/haLanguageService.ts
  src/server/server.ts
  src/test/suite/area-validation-mock.test.ts
  src/test/suite/device-validation-mock.test.ts
  src/test/suite/entity-validation-mock.test.ts
  src/test/suite/floor-validation-mock.test.ts
  src/test/suite/label-validation-mock.test.ts
  src/test/suite/secrets-validation-mock.test.ts
  src/test/suite/service-validation-mock.test.ts
Labels: enhancement
