Repository keesschollaart81/vscode-home-assistant, pull requests merged in 2025-05, with the labels that each got.

#3538 Small dependency changes to get extension into a working state
  package-lock.json
  package.json
  src/extension.ts
  src/language-service/package-lock.json
  src/language-service/package.json
  src/language-service/src/haLanguageService.ts
  src/server/server.ts
Labels: dependencies

#3545 Add & cleanup using stylistic
  .vscode/tasks.json
  eslint.config.js
  eslint.config.mjs
  package-lock.json
  package.json
  src/language-service/package-lock.json
  src/language-service/src/completionHelpers/areas.ts
  src/language-service/src/completionHelpers/domains.ts
  src/language-service/src/completionHelpers/entityIds.ts
  src/language-service/src/completionHelpers/floors.ts
  src/language-service/src/completionHelpers/labels.ts
  src/language-service/src/completionHelpers/services.ts
  src/language-service/src/configuration.ts
  src/language-service/src/definition/scripts.ts
  src/language-service/src/haConfig/haConfig.ts
  src/language-service/src/haConfig/haYamlFile.ts
  src/language-service/src/haLanguageService.ts
  src/language-service/src/home-assistant/haConnection.ts
  src/language-service/src/schemas/configuration.ts
  src/language-service/src/schemas/integrations/actions.ts
  src/language-service/src/schemas/integrations/conditions.ts
  src/language-service/src/schemas/integrations/core/conversation.ts
  src/language-service/src/schemas/integrations/core/homeassistant.ts
  src/language-service/src/schemas/integrations/core/mqtt.ts
  src/language-service/src/schemas/integrations/core/scene.ts
  src/language-service/src/schemas/integrations/selectors.ts
  src/language-service/src/schemas/lovelace/elements.ts
  src/language-service/src/schemas/schemaService.ts
  src/language-service/src/schemas/types.ts
  src/server/fileAccessor.ts
  src/server/server.ts
Labels: enhancement

#3546 Optimize schema generation in compile script
  package.json
  src/language-service/tsconfig.json
Labels: enhancement

#3547 Refactor parameter names to improve clarity and enable unused parameter checks
  src/extension.ts
  src/language-service/src/completionHelpers/areas.ts
  src/language-service/src/completionHelpers/domains.ts
  src/language-service/src/completionHelpers/entityIds.ts
  src/language-service/src/completionHelpers/floors.ts
  src/language-service/src/completionHelpers/labels.ts
  src/language-service/src/completionHelpers/services.ts
  src/language-service/tsconfig.json
  src/server/server.ts
  tsconfig.json
Labels: enhancement

#3548 Change action_topic type to string
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: bug

#3551 Migrate/implement the use of VSCode SecretStorage for tokens and URLs
  package-lock.json
  package.json
  src/auth/commands.ts
  src/auth/debug.ts
  src/auth/manager.ts
  src/auth/middleware.ts
  src/auth/repair.ts
  src/extension.ts
  src/language-service/src/configuration.ts
  src/language-service/src/home-assistant/haConnection.ts
  src/language-service/src/home-assistant/socket.ts
  src/server/server.ts
Labels: enhancement

#3552 Set default instance URL when setting up connection
  src/auth/commands.ts
Labels: enhancement

#3553 Add Home Assistant status bar item
  package.json
  src/extension.ts
  src/language-service/src/home-assistant/haConnection.ts
  src/server/server.ts
  src/status/statusBar.ts
Labels: enhancement

#3312 Add missing MQTT items for fans
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: yaml

#3235 Add support for alternative template schema
  src/language-service/src/schemas/integrations/core/template.ts
Labels: yaml

#3554 Refactor all reload command into a submenu
  package.json
  src/commands/reloadCommands.ts
  src/extension.ts
Labels: enhancement

#3557 Upgrade yaml-language-server to 1.18.0 and yaml to 2.8.0
  .github/workflows/github-actions-vscode-extension.yml
  .vscode-test.js
  .vscode/launch.json
  package-lock.json
  package.json
  src/language-service/package-lock.json
  src/language-service/package.json
  src/language-service/src/haConfig/haYamlFile.ts
  src/language-service/src/haLanguageService.ts
  src/server/server.ts
  src/test/runTest.ts
  src/test/suite/entity-service-completion.test.ts
  src/test/suite/error-handling.test.ts
  src/test/suite/extension.test.ts
  src/test/suite/index.ts
  src/test/suite/language-features.test.ts
  src/test/suite/performance.test.ts
  src/test/suite/schema-validation.test.ts
  src/test/suite/script-references.test.ts
  src/test/suite/yaml-position-tracking.test.ts
  test-workspace/.vscode/settings.json
  test-workspace/configuration.yaml
  test-workspace/empty.yaml
  test-workspace/test-completion.yaml
  test-workspace/test-error-handling.yaml
  test-workspace/test-goto-definition.yaml
  test-workspace/test-invalid-automation.yaml
  test-workspace/test-performance.yaml
  test-workspace/test-position-tracking.yaml
  test-workspace/test-schema-validation.yaml
  test-workspace/test-script-validation.yaml
  test-workspace/test-sensor-validation.yaml
Labels: enhancement

#3559 Update vscode-json-languageservice & vscode-languageserver
  package-lock.json
  package.json
  src/extension.ts
Labels: enhancement

#3561 Remove position tracking performance test, it is flaky as hell
  src/test/suite/performance.test.ts
Labels: bug

#3563 Add icon property to AttributeRow
  src/language-service/src/schemas/lovelace/rows.ts
Labels: yaml

#3562 Add support for MQTT Switch entities
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: yaml

#3565 Add unknown area_id checks/warnings detected
  src/language-service/src/haLanguageService.ts
  src/test/suite/area-validation-mock.test.ts
  test-workspace/test-area-validation.yaml
  test-workspace/test-performance.yaml
Labels: enhancement

#3566 Add support for MQTT Humidifier entities
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: yaml

#3567 Fix Jinja2 operator beginning pattern to include whitespace
  syntaxes/home-assistant/jinja-braces-block.tmLanguage
Labels: bug

#3568 Add support for MQTT Button entities
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: yaml

#3569 Add support for MQTT siren entities
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: yaml

#3570 Add support for MQTT scene entities
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: yaml

#3574 Add autocompletion for secrets from secrets.yaml
  README.md
  src/language-service/src/completionHelpers/secrets.ts
  src/language-service/src/haConfig/haConfig.ts
  src/language-service/src/haLanguageService.ts
Labels: enhancement

#3576 Add goto definition for secrets
  src/language-service/src/definition/secrets.ts
  src/server/server.ts
  src/test/suite/secrets-definition.test.ts
  test-workspace/test-missing-secrets.yaml
  test-workspace/test-secrets-goto.yaml
  test-workspace/test-secrets-invalid.yaml
  test-workspace/test-secrets-nested.yaml
Labels: enhancement

#3577 Add entity information on hover of entity_id
  src/language-service/src/completionHelpers/entityIds.ts
  src/language-service/src/completionHelpers/iconRenderer.ts
  src/language-service/src/haLanguageService.ts
  src/language-service/src/home-assistant/haConnection.ts
  src/language-service/src/schemas/integrations/core/mqtt.ts
  src/test/suite/area-validation-mock.test.ts
  src/test/suite/entity-validation-mock.test.ts
  src/test/suite/secrets-validation-mock.test.ts
  test-workspace/test-device-area-hover.yaml
  test-workspace/test-entity-hover.yaml
Labels: enhancement

#3578 Only show config attribute description when hovering the YAML key
  src/language-service/src/haLanguageService.ts
  test-workspace/test-hover-behavior.yaml
Labels: enhancement

#3579 Add unknown device_id checks/warnings detected
  src/language-service/src/completionHelpers/deviceIds.ts
  src/language-service/src/haLanguageService.ts
  src/language-service/src/home-assistant/haConnection.ts
  src/test/suite/area-validation-mock.test.ts
  src/test/suite/device-validation-mock.test.ts
  src/test/suite/entity-validation-mock.test.ts
  src/test/suite/secrets-validation-mock.test.ts
  test-workspace/test-device-validation.yaml
Labels: enhancement

#3580 Add service action information on hover of action identifier
  src/language-service/src/completionHelpers/services.ts
  src/language-service/src/haLanguageService.ts
  src/language-service/src/home-assistant/haConnection.ts
  src/test/suite/area-validation-mock.test.ts
  src/test/suite/device-validation-mock.test.ts
  src/test/suite/entity-validation-mock.test.ts
  src/test/suite/secrets-validation-mock.test.ts
Labels: enhancement

#3581 Add unknown label_id checks/warnings detected
  src/language-service/src/haLanguageService.ts
  src/test/suite/label-validation-mock.test.ts
  test-workspace/test-label-validation.yaml
Labels: enhancement

#3583 Add unknown floor_id checks/warnings detected
  src/language-service/src/haLanguageService.ts
  src/test/suite/floor-validation-mock.test.ts
  src/test/suite/label-validation-mock.test.ts
  test-workspace/test-floor-validation.yaml
Labels: enhancement

#3586 Update KNX integration YAML to match current HA source code
  src/language-service/src/schemas/integrations/core/knx.ts
Labels: yaml

#3587 Update MQTT schemas for the alarm control panel
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: yaml

#3588 Add support for Modbus
  src/language-service/src/schemas/configuration.ts
  src/language-service/src/schemas/integrations/core/index.d.ts
  src/language-service/src/schemas/integrations/core/modbus.ts
Labels: yaml

#3590 Add support for Alert
  src/language-service/src/schemas/configuration.ts
  src/language-service/src/schemas/integrations/core/alert.ts
  src/language-service/src/schemas/integrations/core/index.d.ts
Labels: yaml

#3591 Update MQTT schemas for device trackers
  src/language-service/src/schemas/integrations/core/mqtt.ts
Labels: yaml

#3592 Support action for auto completion in addition to service
  src/language-service/src/completionHelpers/services.ts
Labels: bug

#3593 Add unknown service actions calls checks/warnings detected
  README.md
  src/language-service/src/completionHelpers/services.ts
  src/language-service/src/haLanguageService.ts
  src/snippets/homeassistant_automation.json
  src/test/suite/service-validation-mock.test.ts
  test-workspace/test-service-validation.yaml
Labels: enhancement

#3594 Add support for camera proxy
  src/language-service/src/schemas/integrations/core/camera.ts
  src/language-service/src/schemas/integrations/core/index.d.ts
  src/language-service/src/schemas/integrations/core/proxy.ts
  test-workspace/test-proxy-camera.yaml
Labels: yaml

#3595 Add support for compensation helper
  src/language-service/src/schemas/configuration.ts
  src/language-service/src/schemas/integrations/core/compensation.ts
  src/language-service/src/schemas/integrations/core/index.d.ts
  test-workspace/test-compensation.yaml
Labels: yaml

#3599 Update Thermostat & Humidifier card schemas
  src/language-service/src/schemas/lovelace/cards/humidifier.ts
  src/language-service/src/schemas/lovelace/cards/thermostat.ts
Labels: yaml

#3600 Fix RepeatAction for_each type to accept an array of Data
  src/language-service/src/schemas/integrations/actions.ts
Labels: bug

#3602 Add error handling and display render issue when rendering template
  src/language-service/src/home-assistant/haConnection.ts
  src/server/server.ts
Labels: enhancement

#3605 Don't throw warnings for Long-Lived Access Tokens
  src/auth/debug.ts
  src/language-service/src/home-assistant/socket.ts
Labels: bug

#3607 Do not migrate environment authentication information
  src/auth/middleware.ts
Labels: bug

#3618 Update KNX schema
  src/language-service/src/schemas/integrations/core/knx.ts
Labels: yaml
